-- TABELAS A SEREM CRIADAS E RESPECTIVOS RELACIONAMENTOS

Logradouro: ID LOG(PK), LOGRADOURO, NÚMERO, CEP, BAIRRO(FK);
Bairro: ID BAIRRO(PK), NOME, CIDADE(FK);
Cidade: ID CIDADE(PK), NOME, ESTADO(FK); 
Estado: ID ESTADO(PK), NOME;
Cliente: ID CLIENTE(PK), NOME, LOGRADOURO(FK), SEXO, EST CIVIL, NASC, DATA CADASTRO, DESC;
Loja: ID LOJA(PK), LOGRADOURO(FK), GERENTE;
Setor: ID SETOR(PK), NOME, PROCENTAGEM DESC;
ProdutoS: ID PRODUTO(PK), NOME, VALOR, QUANTIDADE, DESCRICAO, SETOR(FK);
Lista Produtos: COD_NOTA, COD_PRODUTO(FK), DESC_TOTAL, VALOR_C_DESC;
Pedidos: ID_PEDIDO, QTD_PROD, VALOR TOAL SEM DESCONTO;
Nota Fiscal: ID NTFL(PK), LOJA(FK), VENDEDOR, CLIENTE(FK), QNTD PRODT, TOTAL DESC, VALOR TOAL, VALOR PAGO, DATA;
Lista Vendas: LOJA(FK), COD NTFL(FK), DATA;



CREATE TABLE ESTADO(
    ID_ESTADO    NUMBER(6) NOT NULL 
      CONSTRAINT PK_ESTADO PRIMARY KEY,
    NOME        VARCHAR2(20) NOT NULL
);

CREATE TABLE CIDADE (
    ID_CIDADE   NUMBER(6) NOT NULL
        CONSTRAINT PK_ID_CIDADE PRIMARY KEY,
    NOME        VARCHAR2(20) NOT NULL,
    COD_ESTADO  NUMBER(6)
        CONSTRAINT FK_COD_ESTADO REFERENCES ESTADO (ID_ESTADO)
);

CREATE TABLE BAIRRO (
    ID_BAIRRO   NUMBER(6)
        CONSTRAINT PK_ID_BAIRRO PRIMARY KEY,
    NOME        VARCHAR2(20) NOT NULL,
    COD_CIDADE  NUMBER(6)
        CONSTRAINT FK_COD_CIDADE REFERENCES CIDADE (ID_CIDADE)
);

CREATE TABLE LOGRADOURO (
    ID_LOG      NUMBER(6)
        CONSTRAINT PK_ID_LOG PRIMARY KEY,
    LOGRADOURO  VARCHAR(50) NOT NULL,
    NÚMERO      NUMBER(8),
    CEP         CHAR(9),
    COD_BAIRRO      NUMBER(6)
        CONSTRAINT FK_COD_BAIRRO REFERENCES BAIRRO (ID_BAIRRO)
);

CREATE TABLE CLIENTE (
    ID_CLIENTE      NUMBER(6)
        CONSTRAINT PK_ID_CLIENTE PRIMARY KEY,
    NOME            VARCHAR2(50) NOT NULL,
    COD_LOGRADOURO      NUMBER(6)
        CONSTRAINT FK_COD_LOG REFERENCES LOGRADOURO (ID_LOG),
    SEXO            CHAR(1) CHECK (sexo IN ('M', 'F')),
    EST_CIVIL       VARCHAR2(10),
    NASCIMENTO      DATE,
    DATA_CADASTRO   DATE,
    DESCONTO        NUMBER(4,2)
);

CREATE TABLE LOJA (
    ID_LOJA     NUMBER(6)
        CONSTRAINT PK_ID_LOJA PRIMARY KEY,
    GERENTE     VARCHAR2(50) UNIQUE NOT NULL,
    COD_LOG     NUMBER(6)
        CONSTRAINT FK_COD_LOG_LOJA REFERENCES LOGRADOURO (ID_LOG)
);

CREATE TABLE SETOR (
    ID_SETOR        NUMBER(6)
        CONSTRAINT PK_ID_SETOR PRIMARY KEY,
    NOME            VARCHAR(20) NOT NULL,
    PORC_DESCONTO   NUMBER(4,2)
);

CREATE TABLE PRODUTOS (
    ID_PROD     NUMBER(8)
        CONSTRAINT PK_ID_PROD PRIMARY KEY,
    NOME        VARCHAR2(30) NOT NULL,
    VALOR       NUMBER(8,2) NOT NULL,
    QUANTIDADE  NUMBER(10) NOT NULL,
    DESCRICAO   VARCHAR2(100),
    COD_SETOR   NUMBER(6)
        CONSTRAINT FK_COD_SETOR REFERENCES SETOR (ID_SETOR)     
);

CREATE TABLE LISTA_PRODUTOS (
    COD_NOTA NUMBER(6)
        CONSTRAINT FK_COD_NOTA_LISTA REFERENCES NOTA_FISCAL(ID_NOTA),
    COD_PRODUTO NUMBER(8)
        CONSTRAINT FK_COD_PROD_LISTA REFERENCES PRODUTOS(ID_PROD),
    DESC_TOTAL   NUMBER(4,2),
    VALOR_C_DESC NUMBER(8,2)
);

CREATE TABLE PEDIDOS (
    ID_PEDIDO       NUMBER(6),
    QTD_PROD        NUMBER(8),
    VALOR_S_DESC    NUMBER(8,2)
);

CREATE TABLE NOTA_FISCAL (
    ID_NOTA         NUMBER(6)
        CONSTRAINT PK_ID_NOTA PRIMARY KEY,
    VENDEDOR        VARCHAR2(20) NOT NULL,
    COD_LOJA        NUMBER(6)
        CONSTRAINT COD_LOJA_NOTA REFERENCES LOJA (ID_LOJA),
    COD_CLIENTE     NUMBER(6) 
        CONSTRAINT FK_COD_CLIENTE REFERENCES CLIENTE (ID_CLIENTE),
    QTD_PODUTO      NUMBER(4) NOT NULL,
    TOTAL_S_DESC    NUMBER(8,2),
    TOTAL_C_DESC    NUMBER(8,2),
    VALOR_FINAL     NUMBER(8,2),
    VALOR_PAGO      NUMBER(8,2),
    DATA_VENDA      DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE VENDAS_GERAL (
    COD_LOJA    NUMBER(6)
        CONSTRAINT COD_LOJA_VENDAS REFERENCES LOJA(ID_LOJA),
    COD_NOTAF   NUMBER(6)
        CONSTRAINT COD_NOTA_VENDAS REFERENCES NOTA_FISCAL(ID_NOTA),
    DATA_VENDA  DATE DEFAULT SYSDATE NOT NULL
);

DROP TABLE NOTA_FISCAL;
