-- EXISTEM DUAS POSSÍVEIS AÇÕES, UM PRA CADASTRAR CLIENTES NOVOS
-- E OUTRO PRA IR DIRETO PRA COMPRA NO CASO DO 
-- CLIENTE JA SER CADASTRADO NO SISTEMA

-- SEM CADASTRO:
-- 1 - LOGRADOURO
EXECUTE PRC_ADD_LOGRADOURO (P_ID, P_LOG, P_NUM, P_CEP, P_BAIRRO, P_COMANDO);
-- 2 - DADOS CLIENTE
EXECUTE PRC_DML_CLIENTE(P_ID,P_NOME,P_COD_LOG,P_SEXO,P_EST_CV,P_NASC,P_DATA_CDT,P_DESC,P_COMANDO);

-- COM CADASTRO:
-- 3 - COMPRA

-- GERAR NOVO CÓDIGO DE NOTA FISCAL
SELECT SEQ_NOTA.NEXTVAL FROM DUAL;
-- INSERIR OS PRODUTOS DA COMPRA
EXECUTE PRC_LISTA_PROD(ID PEDIDO, ID PRODUTP, QUANTIDADE);
-- GERAR PEDIDO COM O CÓDIGO DA NOTA
EXECUTE PRC_PEDIDOS (ID PEDIDO);
-- GERAR NOTA FISCAL
EXECUTE PRC_COMPRA(ID PEDIDO, VENDEDOR, ID LOJA, ID CLIENTE, VALOR PAGO);

-- CHECAR TABELAS ALTERADAS
SELECT *
FROM LOGRADOURO;

SELECT * 
FROM CLIENTE;

SELECT * 
FROM NOTA_FISCAL;

SELECT * 
FROM VENDAS_GERAIS;
